apiVersion: certmanager.step.sm/v1beta1
kind: StepClusterIssuer
metadata:
  name: step-ca-issuer
spec:
  url: https://host.k3d.internal:19443
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ4RENDQVdxZ0F3SUJBZ0lSQUs2am5vOUFDV0k3Y0ZGT1FuM1JMUDh3Q2dZSUtvWkl6ajBFQXdJd1FERWEKTUJnR0ExVUVDaE1SVTNSbGNDQkRaWEowYVdacFkyRjBaWE14SWpBZ0JnTlZCQU1UR1ZOMFpYQWdRMlZ5ZEdsbQphV05oZEdWeklGSnZiM1FnUTBFd0hoY05Nall3TWpJd01qQXlOekF5V2hjTk16WXdNakU0TWpBeU56QXlXakJBCk1Sb3dHQVlEVlFRS0V4RlRkR1Z3SUVObGNuUnBabWxqWVhSbGN6RWlNQ0FHQTFVRUF4TVpVM1JsY0NCRFpYSjAKYVdacFkyRjBaWE1nVW05dmRDQkRRVEJaTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEEwSUFCS2VGWXkzYwpTWkFlakpqZXZxenVpY3Y0RFhIM3FCOHZteHp1dmUxZzhQZ0k1M205Wm0vdUt6cHdJMitwQ3Q5dXJIV1RnYTZoCmZHN2hyM2xHa3NnNUlKQ2pSVEJETUE0R0ExVWREd0VCL3dRRUF3SUJCakFTQmdOVkhSTUJBZjhFQ0RBR0FRSC8KQWdFQk1CMEdBMVVkRGdRV0JCUlBLanZOMGVVY3BGNVptdDhSYk9Od0NhQk1BREFLQmdncWhrak9QUVFEQWdOSQpBREJGQWlFQTI4VUNTbFQyczdFaS9xU2lEQjRESW9tb3YrN095b1RCTE5TRDNUbGxCd1lDSUJYRDk5TXdDdGJVCmUzRFY3OSthc3Y0Z1l0SlgzRDNtaVNwV09QMDBHYm9jCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  provisioner:
    name: admin
    kid: GJEuVrlyR686JcKgxBZ2lppg2jx0IUz-b-ENjgv3cAU
    passwordRef:
      namespace: cert-manager
      name: step-issuer-provisioner-password
      key: password
