apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: podinfo
  namespace: apps
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - apps
  selector:
    matchLabels:
      app: podinfo
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 30s
