apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: java-api
spec:
  replicas: 1
  strategy:
    canary:
      steps:
        - setWeight: 100
  template:
    spec:
      containers:
        - name: java-api
          image: k3d-sgp-registry.localhost:5001/java-api-with-otlp-sdk@sha256:b49d2efb5c1817b2d01ed958e7b0949ac9532ff25f6f873f7105d3b1d6d66dc6
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_ENV
              value: dev
            - name: OTLP_TRACES_ENDPOINT
              value: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318/v1/traces
            - name: OTLP_METRICS_ENDPOINT
              value: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318/v1/metrics
            - name: OTLP_LOGS_ENDPOINT
              value: http://otel-collector-opentelemetry-collector.observability.svc.cluster.local:4318/v1/logs
          envFrom:
            - secretRef:
                name: java-api-db-runtime
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            privileged: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
