apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: java-api-success-rate
spec:
  metrics:
    - name: success-rate
      interval: 30s
      count: 4
      failureLimit: 1
      successCondition: result[0] >= 0.995
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          query: |
            (
              sum(rate(http_server_requests_seconds_count{namespace="apps",app="java-api",status!~"5.."}[1m]))
              /
              sum(rate(http_server_requests_seconds_count{namespace="apps",app="java-api"}[1m]))
            ) or vector(0)
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: java-api-latency-p95
spec:
  metrics:
    - name: latency-p95
      interval: 30s
      count: 4
      failureLimit: 1
      successCondition: result[0] <= 0.40
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          query: |
            histogram_quantile(
              0.95,
              sum by (le) (
                rate(http_server_requests_seconds_bucket{namespace="apps",app="java-api"}[2m])
              )
            ) or vector(999)
