apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: java-api
  namespace: apps
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - apps
  selector:
    matchLabels:
      app: java-api
  podMetricsEndpoints:
    - port: http
      path: /actuator/prometheus
      interval: 30s
