apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: http://host.k3d.internal:18200
      path: kv
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes-homolog
          role: eso-homolog
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
