apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: podinfo-slo-alerts
  namespace: observability
spec:
  groups:
    - name: podinfo-burn-rate
      rules:
        - alert: PodinfoAvailabilityBurnRateFast
          expr: |
            (
              1 - (
                sum(rate(http_requests_total{namespace="apps",app="podinfo",code=~"2..|3.."}[5m]))
                /
                sum(rate(http_requests_total{namespace="apps",app="podinfo"}[5m]))
              )
            ) > (1 - 0.995) * 14.4
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Podinfo burn rate is too high (fast window)"
            runbook_url: "runbooks/rollout-degraded.md"
        - alert: PodinfoAvailabilityBurnRateSlow
          expr: |
            (
              1 - (
                sum(rate(http_requests_total{namespace="apps",app="podinfo",code=~"2..|3.."}[1h]))
                /
                sum(rate(http_requests_total{namespace="apps",app="podinfo"}[1h]))
              )
            ) > (1 - 0.995) * 6
          for: 30m
          labels:
            severity: warning
          annotations:
            summary: "Podinfo burn rate is elevated (slow window)"
            runbook_url: "runbooks/rollout-degraded.md"
    - name: podinfo-latency
      rules:
        - alert: PodinfoP95LatencyHigh
          expr: |
            histogram_quantile(
              0.95,
              sum by (le) (
                rate(http_request_duration_seconds_bucket{namespace="apps",app="podinfo"}[5m])
              )
            ) > 0.40
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "Podinfo p95 latency above objective"
            runbook_url: "runbooks/rollout-degraded.md"
