apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-issuer-provisioner-password
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: step-issuer-provisioner-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: apps/pki/step-issuer
        property: provisioner_password
